import{calcularletras} from "./ejercicio1.js";
import{palabrarecortada} from "./ejercicio2.js";
import{separar} from "./ejercicio3.js";
import {repetircad} from "./ejercicio4.js";
console.log('Ejercicio 1');
console.log(calcularletras("arbol"));
console.log('Ejercicio 2');
console.log(palabrarecortada("Hola mundo",7));
console.log('Ejercicio 3');
console.log(separar("Hola que-tal","-"));
console.log('Ejercicio 4');
repetircad("hola  mundo", 2);